<a href="https://colab.research.google.com/github/MaitreePimple/ETL-Projects-/blob/main/ETL_of_sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sales_data.csv")

In [3]:
df.dropna(inplace = True)
df.drop_duplicates(inplace = True)

In [4]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

In [13]:
df['Revenue'] = df['Unit Cost'] * df['Unit Price']

In [14]:
df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Revenue
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-05-28,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50,40696.7376
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-08-22,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36,24089.5270
2,Europe,Russia,Office Supplies,Offline,L,2014-05-02,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75,341859.2016
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-06-20,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82,64.5636
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2013-02-01,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50,341859.2016

In [15]:
df.to_csv("Clean Sales Data.csv", index= False)

In [16]:
print("ETL Process Completed")

ETL Process Completed

In [18]:
df.describe()

,Order Date,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Revenue
count,100,1.000000e+02,100.000000,100.000000,100.000000,1.000000e+02,1.000000e+02,1.000000e+02,100.000000
mean,2013-09-16 14:09:36,5.550204e+08,5128.710000,276.761300,191.048000,1.373488e+06,9.318057e+05,4.416820e+05,96212.859288
min,2010-02-02 00:00:00,1.146066e+08,124.000000,9.330000,6.920000,4.870260e+03,3.612240e+03,1.258020e+03,64.563600
25%,2012-02-14 12:00:00,3.389225e+08,2836.250000,81.730000,35.840000,2.687212e+05,1.688680e+05,1.214436e+05,3916.595200
50%,2013-07-12 12:00:00,5.577086e+08,5382.500000,179.880000,107.275000,7.523144e+05,3.635664e+05,2.907680e+05,19478.461100
75%,2015-04-07 00:00:00,7.907551e+08,7369.000000,437.200000,263.330000,2.212045e+06,1.613870e+06,6.358288e+05,115127.876000
max,2017-05-22 00:00:00,9.940222e+08,9925.000000,668.270000,524.960000,5.997055e+06,4.509794e+06,1.719922e+06,341859.201600
std,NaN,2.606153e+08,2794.484562,235.592241,188.208181,1.460029e+06,1.083938e+06,4.385379e+05,132167.365200

In [21]:
df = df[df['Revenue'] > 0]

In [23]:
df.sort_values (by="Revenue" , ascending = False)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Revenue
2,Europe,Russia,Office Supplies,Offline,L,2014-05-02,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75,341859.2016
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2013-02-01,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50,341859.2016
32,Australia and Oceania,Australia,Office Supplies,Online,C,2015-10-27,158535134,11/25/2015,2924,651.21,524.96,1904138.04,1534983.04,369155.00,341859.2016
39,Europe,Bulgaria,Office Supplies,Online,M,2012-02-16,189965903,2/28/2012,3987,651.21,524.96,2596374.27,2093015.52,503358.75,341859.2016
68,Europe,Lithuania,Office Supplies,Offline,H,2010-10-24,166460740,11/17/2010,8287,651.21,524.96,5396577.27,4350343.52,1046233.75,341859.2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,Sub-Saharan Africa,Lesotho,Fruits,Online,L,2013-08-18,918419539,9/18/2013,9606,9.33,6.92,89623.98,66473.52,23150.46,64.5636
54,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Offline,H,2013-09-17,508980977,10/24/2013,7637,9.33,6.92,71253.21,52848.04,18405.17,64.5636
71,Middle East and North Africa,Libya,Fruits,Online,L,2015-08-14,816200339,9/30/2015,673,9.33,6.92,6279.09,4657.16,1621.93,64.5636
88,Middle East and North Africa,Kuwait,Fruits,Online,M,2012-04-30,513417565,5/18/2012,522,9.33,6.92,4870.26,3612.24,1258.02,64.5636
96,Asia,Malaysia,Fruits,Offline,L,2011-11-11,810711038,12/28/2011,6267,9.33,6.92,58471.11,43367.64,15103.47,64.5636